# Generated by Django 5.1.7 on 2025-03-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('agent', models.CharField(max_length=255)),
                ('agent_rating', models.FloatField()),
            ],
            options={
                'db_table': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=255)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('stops', models.IntegerField()),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_id', models.CharField(max_length=255)),
                ('duration_mins', models.IntegerField()),
            ],
            options={
                'db_table': 'legs',
            },
        ),
        migrations.CreateModel(
            name='ItineraryLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.itinerary')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.leg')),
            ],
            options={
                'db_table': 'itinerary_legs',
                'unique_together': {('itinerary', 'leg')},
            },
        ),
    ]
