# Generated by Django 5.1.7 on 2025-03-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
    ]
